In [1]:
import pandas as pd
import  numpy as np

In [2]:
pd.read_csv('ert.csv')

enrollee_id      city  city_development_index  gender  \
0            16548   city_33                   0.448     NaN   
1            12036   city_28                   0.939    Male   
2            11061  city_103                   0.920    Male   
3             5032  city_104                   0.924    Male   
4            17599   city_77                   0.830    Male   
5            19314  city_160                   0.920    Male   
6            12365   city_21                   0.624    Male   
7            22696  city_114                   0.926    Male   
8            16083  city_103                   0.920    Male   
9            33240  city_103                   0.920    Male   
10             813  city_103                   0.920    Male   
11            1362   city_16                   0.910  Female   
12            3821  city_103                   0.920    Male   
13           26316   city_21                   0.624    Male   
14           29269   city_67                   0.855    Male   
15           22524   city_50                   0.896    Male   
16           30407   city_71                   0.884     NaN   
17             863  city_103                   0.920    Male   
18           27743  city_103                   0.920    Male   
19           29303   city_71                   0.884    Male   
20            1019   city_50                   0.896     NaN   
21            8819  city_103                   0.920    Male   
22            5397  city_103                   0.920  Female   
23           14697  city_136                   0.897     NaN   
24           10407  city_103                   0.920  Female   
25           19224   city_59                   0.775    Male   
26             735  city_103                   0.920    Male   
27           14106  city_103                   0.920  Female   
28             858  city_103                   0.920    Male   
29            9061   city_67                   0.855    Male   
...            ...       ...                     ...     ...   
14991          629   city_97                   0.925    Male   
14992        28387   city_16                   0.910    Male   
14993         3798  city_160                   0.920    Male   
14994        12120   city_98                   0.949     NaN   
14995        21396  city_102                   0.804     NaN   
14996        10500   city_67                   0.855  Female   
14997         5419  city_103                   0.920    Male   
14998        25471  city_103                   0.920     NaN   
14999         4295  city_114                   0.926    Male   
15000        15693   city_28                   0.939     NaN   
15001          588  city_114                   0.926    Male   
15002          383   city_75                   0.939  Female   
15003        14190   city_21                   0.624    Male   
15004        14879   city_16                   0.910     NaN   
15005         6509   city_21                   0.624    Male   
15006        16020   city_73                   0.754    Male   
15007        31215  city_103                   0.920    Male   
15008        23432   city_90                   0.698     NaN   
15009         8556   city_71                   0.884     NaN   
15010         2808   city_23                   0.899    Male   
15011        30530   city_21                   0.624     NaN   
15012        11408  city_103                   0.920    Male   
15013        23745  city_134                   0.698     NaN   
15014        14805   city_16                   0.910     NaN   
15015        14836  city_173                   0.878    Male   
15016        11308   city_46                   0.762     NaN   
15017        14612   city_21                   0.624    Male   
15018        33346   city_16                   0.910    Male   
15019        14506   city_64                   0.666     NaN   
15020        32641   city_21                   0.624    Male   

           relevent_experience enrolle

In [3]:
a = pd.read_csv('ert.csv')

In [5]:
range(a.shape[0])

range(0, 15021)

In [103]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73147 entries, 0 to 73146
Data columns (total 16 columns):
id                           73147 non-null object
program_id                   73147 non-null object
program_type                 73147 non-null object
program_duration             73147 non-null int64
test_id                      73147 non-null int64
test_type                    73147 non-null object
difficulty_level             73147 non-null object
trainee_id                   73147 non-null int64
gender                       73147 non-null object
education                    73147 non-null object
city_tier                    73147 non-null int64
age                          45418 non-null float64
total_programs_enrolled      73147 non-null int64
is_handicapped               73147 non-null object
trainee_engagement_rating    73070 non-null float64
is_pass                      73147 non-null int64
dtypes: float64(2), int64(6), object(8)
memory usage: 8.9+ MB


In [104]:
median = a["age"].median()
a["age"].fillna(median,inplace = True)
a["age"] =np.int64(a["age"])
#a["id"] =np.int64(a["id"])
del a['id']
del a['program_id']
del a['program_type']
#a[""] =np.int64(a["program_id"])
#a["age"] =np.int64(a["age"])
#a["age"] = np.where(a["age"]>38,1,0)

In [105]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73147 entries, 0 to 73146
Data columns (total 13 columns):
program_duration             73147 non-null int64
test_id                      73147 non-null int64
test_type                    73147 non-null object
difficulty_level             73147 non-null object
trainee_id                   73147 non-null int64
gender                       73147 non-null object
education                    73147 non-null object
city_tier                    73147 non-null int64
age                          73147 non-null int64
total_programs_enrolled      73147 non-null int64
is_handicapped               73147 non-null object
trainee_engagement_rating    73070 non-null float64
is_pass                      73147 non-null int64
dtypes: float64(1), int64(7), object(5)
memory usage: 7.3+ MB


In [106]:
b =a["age"].dtype
print(b)
ishand = {'N':0 , 'Y':1}

int64


In [107]:
#df['Sex'] = df['Sex'].apply(lambda x:d[x])
#ishand = {'N':1 , 'Y':0}
a['is_handicapped'] = a['is_handicapped'].apply(lambda x:ishand[x] )
#a["age"] = a["age"]/39

In [108]:
a.head()

program_duration  test_id test_type difficulty_level  trainee_id gender  \
0               136      150   offline     intermediate        9389      M   
1               131       44   offline             easy       16523      F   
2               120      178    online             easy       13987      M   
3               117       32   offline             easy       13158      F   
4               131       84   offline     intermediate       10591      F   

             education  city_tier  age  total_programs_enrolled  \
0        Matriculation          3   24                        5   
1  High School Diploma          4   26                        2   
2        Matriculation          1   40                        1   
3        Matriculation          3   39                        4   
4  High School Diploma          1   42                        2   

   is_handicapped  trainee_engagement_rating  is_pass  
0               0                        1.0        0  
1               0                        3.0        1  
2               0                        2.0        1  
3               0                        1.0        1  
4               0                        4.0        1

In [109]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73147 entries, 0 to 73146
Data columns (total 13 columns):
program_duration             73147 non-null int64
test_id                      73147 non-null int64
test_type                    73147 non-null object
difficulty_level             73147 non-null object
trainee_id                   73147 non-null int64
gender                       73147 non-null object
education                    73147 non-null object
city_tier                    73147 non-null int64
age                          73147 non-null int64
total_programs_enrolled      73147 non-null int64
is_handicapped               73147 non-null int64
trainee_engagement_rating    73070 non-null float64
is_pass                      73147 non-null int64
dtypes: float64(1), int64(8), object(4)
memory usage: 7.3+ MB


In [110]:
median = a["trainee_engagement_rating"].median()
a["trainee_engagement_rating"].fillna(median,inplace = True)
a["trainee_engagement_rating"] = np.int64(a["trainee_engagement_rating"])
#a["trainee_engagement_rating"] = np.where(a["trainee_engagement_rating"]>2.4,1,0)

In [111]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73147 entries, 0 to 73146
Data columns (total 13 columns):
program_duration             73147 non-null int64
test_id                      73147 non-null int64
test_type                    73147 non-null object
difficulty_level             73147 non-null object
trainee_id                   73147 non-null int64
gender                       73147 non-null object
education                    73147 non-null object
city_tier                    73147 non-null int64
age                          73147 non-null int64
total_programs_enrolled      73147 non-null int64
is_handicapped               73147 non-null int64
trainee_engagement_rating    73147 non-null int64
is_pass                      73147 non-null int64
dtypes: int64(9), object(4)
memory usage: 7.3+ MB


In [112]:
a.difficulty_level.unique()
#a.education.unique()

array(['intermediate', 'easy', 'hard', 'vary hard'], dtype=object)

In [113]:
diff = {'easy':0,'intermediate':1,'hard':2,'vary hard':3}

In [114]:
#a['difficulty_level'] = a['difficulty_level'].apply(lambda x:diff[x] )
a['difficulty_level'] = a['difficulty_level'].apply(lambda x:diff[x] )

In [115]:
a.head()

program_duration  test_id test_type  difficulty_level  trainee_id gender  \
0               136      150   offline                 1        9389      M   
1               131       44   offline                 0       16523      F   
2               120      178    online                 0       13987      M   
3               117       32   offline                 0       13158      F   
4               131       84   offline                 1       10591      F   

             education  city_tier  age  total_programs_enrolled  \
0        Matriculation          3   24                        5   
1  High School Diploma          4   26                        2   
2        Matriculation          1   40                        1   
3        Matriculation          3   39                        4   
4  High School Diploma          1   42                        2   

   is_handicapped  trainee_engagement_rating  is_pass  
0               0                          1        0  
1               0                          3        1  
2               0                          2        1  
3               0                          1        1  
4               0                          4        1

In [116]:
print (5)

5


In [117]:
edu = { 'No Qualification':0, 'Matriculation':1, 'High School Diploma':2, 'Bachelors':3, 'Masters':4}

In [118]:
a['education'] = a['education'].apply(lambda x:edu[x] )

In [119]:
a.head()

program_duration  test_id test_type  difficulty_level  trainee_id gender  \
0               136      150   offline                 1        9389      M   
1               131       44   offline                 0       16523      F   
2               120      178    online                 0       13987      M   
3               117       32   offline                 0       13158      F   
4               131       84   offline                 1       10591      F   

   education  city_tier  age  total_programs_enrolled  is_handicapped  \
0          1          3   24                        5               0   
1          2          4   26                        2               0   
2          1          1   40                        1               0   
3          1          3   39                        4               0   
4          2          1   42                        2               0   

   trainee_engagement_rating  is_pass  
0                          1        0  
1                          3        1  
2                          2        1  
3                          1        1  
4                          4        1

In [120]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73147 entries, 0 to 73146
Data columns (total 13 columns):
program_duration             73147 non-null int64
test_id                      73147 non-null int64
test_type                    73147 non-null object
difficulty_level             73147 non-null int64
trainee_id                   73147 non-null int64
gender                       73147 non-null object
education                    73147 non-null int64
city_tier                    73147 non-null int64
age                          73147 non-null int64
total_programs_enrolled      73147 non-null int64
is_handicapped               73147 non-null int64
trainee_engagement_rating    73147 non-null int64
is_pass                      73147 non-null int64
dtypes: int64(11), object(2)
memory usage: 7.3+ MB


In [121]:
tt = { 'offline':0,'online':1}

In [122]:
#tt = { 'offline':0,'online':1}
sex = { 'F':0,'M':1}
a["gender"] = a["gender"].apply(lambda x:sex[x])
a['test_type']= a['test_type'].apply(lambda x:tt[x])

In [123]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73147 entries, 0 to 73146
Data columns (total 13 columns):
program_duration             73147 non-null int64
test_id                      73147 non-null int64
test_type                    73147 non-null int64
difficulty_level             73147 non-null int64
trainee_id                   73147 non-null int64
gender                       73147 non-null int64
education                    73147 non-null int64
city_tier                    73147 non-null int64
age                          73147 non-null int64
total_programs_enrolled      73147 non-null int64
is_handicapped               73147 non-null int64
trainee_engagement_rating    73147 non-null int64
is_pass                      73147 non-null int64
dtypes: int64(13)
memory usage: 7.3 MB


In [124]:
a.info()
corr_matrix = a.corr()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73147 entries, 0 to 73146
Data columns (total 13 columns):
program_duration             73147 non-null int64
test_id                      73147 non-null int64
test_type                    73147 non-null int64
difficulty_level             73147 non-null int64
trainee_id                   73147 non-null int64
gender                       73147 non-null int64
education                    73147 non-null int64
city_tier                    73147 non-null int64
age                          73147 non-null int64
total_programs_enrolled      73147 non-null int64
is_handicapped               73147 non-null int64
trainee_engagement_rating    73147 non-null int64
is_pass                      73147 non-null int64
dtypes: int64(13)
memory usage: 7.3 MB


In [125]:
corr_matrix["is_pass"].sort_values(ascending=True)

difficulty_level            -0.110392
city_tier                   -0.068663
is_handicapped              -0.036967
total_programs_enrolled     -0.031695
program_duration             0.003545
gender                       0.020376
trainee_id                   0.035900
age                          0.058132
test_id                      0.074568
education                    0.082536
test_type                    0.151547
trainee_engagement_rating    0.197369
is_pass                      1.000000
Name: is_pass, dtype: float64

In [126]:

#Target = ['is_pass']

In [127]:
#Helper = ['city_tier', 'test_type', 'education', 'difficulty_level',]
#X= a[Helper]
#Y=a[Target]
a = a.drop('trainee_id',axis=1)


In [128]:
features = np.array(a.drop('is_pass',axis = 1))
print (features[:11])

[[136 150   0   1   1   1   3  24   5   0   1]
 [131  44   0   0   0   2   4  26   2   0   3]
 [120 178   1   0   1   1   1  40   1   0   2]
 [117  32   0   0   0   1   3  39   4   0   1]
 [131  84   0   1   0   2   1  42   2   0   4]
 [134  23   0   1   0   2   1  29   4   0   2]
 [120 144   1   0   1   3   2  48   3   0   3]
 [134  61   1   0   1   1   2  45   1   0   1]
 [134  57   0   0   1   1   4  39   3   0   3]
 [136 153   0   2   1   3   3  28   2   0   4]
 [131  80   0   0   0   2   3  39   2   0   4]]


In [941]:
#from sklearn.model_selection import train_test_split

In [942]:
#xt,xte,yt,yte = train_test_split(X,Y,test_size=0.2,random_state=42)

In [943]:

#print (1)
#fromfrom  sklearnsklearn  importimport  svmsvm

In [944]:
#from sklearn import svm

In [945]:
#clf = svm.LinearSVC()

In [ ]:
#cl
from pandas import read_csv
from sklearn.ensemble import ExtraTreesClassifier
# load data
#url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
#names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
names = ['id','program_id','program_type','program_duration','test_id','test_type','difficulty_level','trainee_id','gender','education','city_tier','age','total_programs_enrolled','is_handicapped','trainee_engagement_rating']
#dataframe = read_csv(url, names=names)
array = a.values
X = array[:,0:12]
Y = array[:,12]
# feature extraction
model = ExtraTreesClassifier()
model.fit(X, Y)
print(model.feature_importances_)






#names = ['id','program_id','program_type','program_duration','test_id','test_type','difficulty_level','trainee_id','gender','education','city_tier','age','total_programs_enrolled','is_handicapped','trainee_engagement_rating']
#dataframe = read_csv(url, names=names)

In [ ]:
train_y = a['is_pass']
#Helper = ['gender','age','city_tier', 'test_type', 'education', 'difficulty_level','is_handicapped','trainee_engagement_rating','program_duration']
Helper = ['city_tier', 'test_id','trainee_engagement_rating','gender','education']
#Create training predictors data
train_X = a[Helper]
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
ran_clf = RandomForestClassifier(n_estimators=10)
log_clf = LogisticRegression()
svm_clf = SVC()
knn_clf = KNeighborsClassifier()
#ada_clf = AdaBoostClassifier(n_estimators=100)
#from sklearn.ensemble import RandomForestRegressor
#from sklearn.naive_bayes import GaussianNB
#my_model = GaussianNB()
#my_model.fit(train_X, train_y)
#voting_clf = VotingClassifier(estimators=[('lr',log_clf),('svc',svm_clf),('knn',knn_clf),('rand',ran_clf)],voting='hard')
#voting_clf.fit(train_X,train_y)
bagging_clf = BaggingClassifier(DecisionTreeClassifier(splitter="random",max_leaf_nodes=16),n_estimators=500,max_samples=1.0,bootstrap=True,n_jobs=-1)
bagging_clf.fit(train_X,train_y)

In [ ]:
test = pd.read_csv('test.csv')
test.head()
test.info()
median1 = test["trainee_engagement_rating"].median()
test["trainee_engagement_rating"].fillna(median1,inplace = True)
test["trainee_engagement_rating"] = np.int64(test["trainee_engagement_rating"])
#test["trainee_engagement_rating"] = np.where(test["trainee_engagement_rating"]>=a["trainee_engagement_rating"].median(),1,0)

ta = { 'offline':0,'online':1}
test['test_type']= test['test_type'].apply(lambda x:tt[x])
edu = { 'No Qualification':0, 'Matriculation':1, 'High School Diploma':2, 'Bachelors':3, 'Masters':4}
test['education'] = test['education'].apply(lambda x:edu[x] )
test['difficulty_level'] = test['difficulty_level'].apply(lambda x:diff[x] )
median = test["age"].median()
test["age"].fillna(median,inplace = True)
test["age"] =np.int64(test["age"])
#test["age"] = np.where(test["age"]>a["age"].median(),1,0)
ishandi = {'N':1 , 'Y':0}
test['is_handicapped'] = test['is_handicapped'].apply(lambda x:ishandi[x] )
sex1 = { 'F':0,'M':1}
test["gender"] = test["gender"].apply(lambda x:sex1[x])

In [83]:
#median1 = test["trainee_engagement_rating"].median()
#test["trainee_engagement_rating"].fillna(median1,inplace = True)
#from sklearn.preprocessing import Imputer
#imp = Imputer( strategy='median')
#new_train = test.drop("trainee_engagement_rating")
#imp.fit(new_train)
#test12 = test[Helper]
#test.drop("trainee_engagement_rating",axis =1)
test.info()
#test.drop("age",axis =1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31349 entries, 0 to 31348
Data columns (total 15 columns):
id                           31349 non-null object
program_id                   31349 non-null object
program_type                 31349 non-null object
program_duration             31349 non-null int64
test_id                      31349 non-null int64
test_type                    31349 non-null int64
difficulty_level             31349 non-null int64
trainee_id                   31349 non-null int64
gender                       31349 non-null int64
education                    31349 non-null int64
city_tier                    31349 non-null int64
age                          31349 non-null int64
total_programs_enrolled      31349 non-null int64
is_handicapped               31349 non-null int64
trainee_engagement_rating    31349 non-null int64
dtypes: int64(12), object(3)
memory usage: 3.6+ MB


In [84]:
#test.drop("age",axis=1)
#Helper1 = ['gender','age','city_tier', 'test_type', 'education', 'difficulty_level','is_handicapped','trainee_engagement_rating','program_duration']
#Helper1 = ['trainee_engagement_rating', 'test_type','age','gender','education']
Helper1 = ['city_tier', 'test_id','trainee_engagement_rating','gender','education']
test_X = test[Helper1]
is_pass_test = bagging_clf.predict(test_X)
#is_pass_test = my_model.predict(test_X)
#from sklearn.metrics import accuracy_score
#accuracy_score()
#voting_clf.predict(test_X)

In [85]:
print(is_pass_test)

len(is_pass_test)

[1 1 1 ... 1 1 1]


31349

In [87]:
my_submission = pd.DataFrame({'id': test.id, 'is_pass': is_pass_test})
# you could use any filename. We choose submission here
my_submission.to_csv('niggd.csv', index=False)

In [391]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31349 entries, 0 to 31348
Data columns (total 15 columns):
id                           31349 non-null object
program_id                   31349 non-null object
program_type                 31349 non-null object
program_duration             31349 non-null int64
test_id                      31349 non-null int64
test_type                    31349 non-null int64
difficulty_level             31349 non-null int64
trainee_id                   31349 non-null int64
gender                       31349 non-null object
education                    31349 non-null int64
city_tier                    31349 non-null int64
age                          31349 non-null float64
total_programs_enrolled      31349 non-null int64
is_handicapped               31349 non-null object
trainee_engagement_rating    31349 non-null float64
dtypes: float64(2), int64(8), object(5)
memory usage: 3.6+ MB


In [172]:
median = test["age"].median()
test["age"].fillna(median,inplace = True)

In [173]:
test.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31349 entries, 0 to 31348
Data columns (total 15 columns):
id                           31349 non-null object
program_id                   31349 non-null object
program_type                 31349 non-null object
program_duration             31349 non-null int64
test_id                      31349 non-null int64
test_type                    31349 non-null int64
difficulty_level             31349 non-null int64
trainee_id                   31349 non-null int64
gender                       31349 non-null object
education                    31349 non-null int64
city_tier                    31349 non-null int64
age                          31349 non-null float64
total_programs_enrolled      31349 non-null int64
is_handicapped               31349 non-null object
trainee_engagement_rating    31349 non-null float64
dtypes: float64(2), int64(8), object(5)
memory usage: 3.6+ MB


In [183]:
a.is_pass

0        0
1        1
2        1
3        1
4        1
5        0
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       0
16       0
17       1
18       0
19       0
20       1
21       0
22       1
23       1
24       1
25       0
26       1
27       1
28       1
29       1
        ..
73117    1
73118    0
73119    0
73120    1
73121    1
73122    0
73123    1
73124    1
73125    1
73126    1
73127    1
73128    1
73129    0
73130    0
73131    1
73132    0
73133    1
73134    0
73135    1
73136    1
73137    1
73138    1
73139    1
73140    1
73141    1
73142    1
73143    1
73144    1
73145    1
73146    1
Name: is_pass, Length: 73147, dtype: int64

In [756]:
a["age"].median()

1.0

2.0

In [1]:
pwd

'C:\\Users\\dell15'

In [29]:
a.values

array([['9389_150', 'Y_1', 'Y', ..., 1, 1, 0],
       ['16523_44', 'T_1', 'T', ..., 1, 3, 1],
       ['13987_178', 'Z_2', 'Z', ..., 1, 2, 1],
       ...,
       ['13063_142', 'Y_2', 'Y', ..., 1, 4, 1],
       ['5667_82', 'V_3', 'V', ..., 1, 2, 1],
       ['4467_119', 'Y_4', 'Y', ..., 1, 4, 1]], dtype=object)

In [30]:
array = a.values
X = array[:,0:15]

In [31]:
X

array([['9389_150', 'Y_1', 'Y', ..., 5, 1, 1],
       ['16523_44', 'T_1', 'T', ..., 2, 1, 3],
       ['13987_178', 'Z_2', 'Z', ..., 1, 1, 2],
       ...,
       ['13063_142', 'Y_2', 'Y', ..., 3, 1, 4],
       ['5667_82', 'V_3', 'V', ..., 2, 1, 2],
       ['4467_119', 'Y_4', 'Y', ..., 2, 1, 4]], dtype=object)

In [34]:
Y = array[:,14]

In [35]:
Y

array([1, 3, 2, ..., 4, 2, 4], dtype=object)

In [130]:
a["program_duration"].median()

131.0

In [132]:
#a.difficulty_level.unique()
a.total_programs_enrolled.unique()

array([ 5,  2,  1,  4,  3,  6,  7, 10, 14,  8, 11,  9, 12], dtype=int64)